variable "proxmox_url" {
  type    = string
  default = ""
}

variable "proxmox_username" {
  type    = string
  default = ""
}

variable "proxmox_password" {
  type    = string
  default = ""
}

variable "template_so_password" {
  type    = string
  default = ""
}

variable "template_so_password_hash" {
  type    = string
  default = ""
}

source "proxmox-iso" "ubuntu-template" {
  proxmox_url              = var.proxmox_url
  username                 = var.proxmox_username
  password                 = var.proxmox_password
  insecure_skip_tls_verify = true
  node                     = "proxmox"
  vm_id                    = 9000
  vm_name                  = "ubuntu-2204-template"
  template_description     = "Ubuntu 22.04 LTS Template generated by Packer on ${timestamp()}"
  iso_url                  = "https://releases.ubuntu.com/22.04/ubuntu-22.04.5-live-server-amd64.iso"
  iso_checksum             = "sha256:9bc6028870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0"
  iso_storage_pool         = "DATASTORE-03-SSD"
  unmount_iso              = true
  qemu_agent               = true
  scsi_controller          = "virtio-scsi-single"

  disks {
    disk_size    = "40G"
    format       = "raw"
    storage_pool = "DATASTORE-03-SSD"
    type         = "scsi"
  }

  cores  = 2
  memory = 2048

  network_adapters {
    model  = "virtio"
    bridge = "vmbr0"
  }

  cloud_init              = true
  cloud_init_storage_pool = "DATASTORE-03-SSD"

  boot_command = [
    "<esc><wait>",
    "e<wait>",
    "<down><down><down><end>",
    " autoinstall ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ---",
    "<wait><f10>"
  ]

  boot_wait = "5s"

  http_directory    = "ubuntu-22-template/http"
  http_bind_address = "0.0.0.0"
  http_port_min     = 8080
  http_port_max     = 8080

  ssh_username           = "ubuntu"
  ssh_password           = var.template_so_password
  ssh_timeout            = "30m"
  ssh_handshake_attempts = 100
  ssh_pty                = true
}

build {
  sources = ["source.proxmox-iso.ubuntu-template"]

  provisioner "file" {
    source      = "ubuntu-22-template/files/99-pve.cfg"
    destination = "/tmp/99-pve.cfg"
  }

  provisioner "shell" {
    inline = [
      "sudo cp /tmp/99-pve.cfg /etc/cloud/cloud.cfg.d/99-pve.cfg",
      "sudo apt-get update",
      "sudo apt-get -y autoremove --purge",
      "sudo apt-get -y clean",
      "sudo apt-get -y autoclean",

      "sudo rm -f /etc/ssh/ssh_host_*",
      "sudo truncate -s 0 /etc/machine-id",
      "sudo rm -f /var/lib/dbus/machine-id",
      "sudo ln -s /etc/machine-id /var/lib/dbus/machine-id",
      "sudo rm -f /root/.bash_history",
      "sudo rm -f /home/ubuntu/.bash_history",
      "sudo dpkg-reconfigure openssh-server",
      "sudo cloud-init clean --logs --seed",
      "sudo rm -rf /var/lib/cloud/*",

      "sudo mkdir -p /var/lib/cloud/instance",
      "sudo touch /var/lib/cloud/instance/boot-finished",
      "sudo rm -f /etc/netplan/00-installer-config.yaml",
      "echo 'network: {version: 2, ethernets: {default: {match: {name: \"e*\"}, dhcp4: true}}}' | sudo tee /etc/netplan/01-netcfg.yaml",

      "sudo sync"
    ]
  }
}

