variable "proxmox_url" {
  type    = string
  default = ""
}

variable "proxmox_username" {
  type    = string
  default = ""
}

variable "proxmox_password" {
  type    = string
  default = ""
}

variable "template_so_password" {
  type    = string
  default = ""
}

variable "template_so_password_hash" {
  type    = string
  default = ""
}

# ✅ Chave pública do bastion que será “baked” no template
# Default: chave padrão do root no bastion (ajuste se necessário)
variable "bastion_ssh_public_key_file" {
  type    = string
  default = "/root/.ssh/id_rsa.pub"
}

source "proxmox-iso" "ubuntu-template" {
  proxmox_url              = var.proxmox_url
  username                 = var.proxmox_username
  password                 = var.proxmox_password
  insecure_skip_tls_verify = true

  node                 = "proxmox"
  vm_id                = 9000
  vm_name              = "ubuntu-2204-template"
  template_description  = "Ubuntu 22.04 LTS Template generated by Packer on ${timestamp()}"

  iso_url          = "https://releases.ubuntu.com/22.04/ubuntu-22.04.5-live-server-amd64.iso"
  iso_checksum     = "sha256:9bc6028870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0"
  iso_storage_pool = "DATASTORE-03-SSD"
  unmount_iso      = true

  qemu_agent      = true
  scsi_controller = "virtio-scsi-single"

  disks {
    disk_size    = "40G"
    format       = "raw"
    storage_pool = "DATASTORE-03-SSD"
    type         = "scsi"
  }

  cores  = 2
  memory = 2048

  network_adapters {
    model  = "virtio"
    bridge = "vmbr0"
  }

  cloud_init              = true
  cloud_init_storage_pool = "DATASTORE-03-SSD"

  boot_command = [
    "<esc><wait>",
    "e<wait>",
    "<down><down><down><end>",
    " autoinstall ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ---",
    "<wait><f10>"
  ]

  boot_wait = "5s"

  http_directory    = "ubuntu-22-template/http"
  http_bind_address = "0.0.0.0"
  http_port_min     = 8080
  http_port_max     = 8080

  # Packer entra via SSH após o primeiro boot do sistema instalado
  ssh_username           = "ubuntu"
  ssh_password           = var.template_so_password
  ssh_timeout            = "30m"
  ssh_handshake_attempts = 100
  ssh_pty                = true
}

build {
  sources = ["source.proxmox-iso.ubuntu-template"]

  provisioner "file" {
    source      = "ubuntu-22-template/files/99-pve.cfg"
    destination = "/tmp/99-pve.cfg"
  }

# provisioner "file" {
#   source      = "ubuntu-22-template/files/98-force-disable.cfg"
#   destination = "/tmp/98-force-disable.cfg"
# }


  # ✅ Envia a chave pública do bastion para dentro da VM (para ser instalada no template)
  provisioner "file" {
    source      = var.bastion_ssh_public_key_file
    destination = "/tmp/bastion_id_rsa.pub"
  }

  provisioner "shell" {
    inline = [
      # cloud-init tweaks do repo
      "sudo cp /tmp/99-pve.cfg /etc/cloud/cloud.cfg.d/99-pve.cfg",

      # ✅ “Relação de confiança” com bastion (ubuntu e root)
      "sudo install -d -m 700 -o ubuntu -g ubuntu /home/ubuntu/.ssh",
      "sudo install -m 600 -o ubuntu -g ubuntu /tmp/bastion_id_rsa.pub /home/ubuntu/.ssh/authorized_keys",
      "sudo install -d -m 700 -o root -g root /root/.ssh",
      "sudo install -m 600 -o root -g root /tmp/bastion_id_rsa.pub /root/.ssh/authorized_keys",

      # ✅ Permite root por chave (recomendado) e mantém senha habilitada para ubuntu (como no seu fluxo)
      "sudo sed -i 's/^#\\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config || true",
      "sudo sed -i 's/^#\\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config || true",
      "sudo systemctl restart ssh || true",

      # ✅ Atualizações e limpeza (noninteractive de verdade)
      "sudo bash -lc 'export DEBIAN_FRONTEND=noninteractive; printf \"Dpkg::Options { \\\"--force-confdef\\\"; \\\"--force-confold\\\"; }\\n\" > /etc/apt/apt.conf.d/90packer-noninteractive'",
      "sudo bash -lc 'systemctl stop apt-daily.service apt-daily-upgrade.service unattended-upgrades.service 2>/dev/null || true'",
      "sudo bash -lc \"printf '$nrconf{restart} = \\\"a\\\";\\n$nrconf{kernelhints} = -1;\\n' > /etc/needrestart/needrestart.conf\"",
      "sudo bash -lc 'export DEBIAN_FRONTEND=noninteractive; apt-get update'",
      "sudo bash -lc 'export DEBIAN_FRONTEND=noninteractive; apt-get -y dist-upgrade'",
      "sudo bash -lc 'export DEBIAN_FRONTEND=noninteractive; apt-get -y autoremove --purge'",
      "sudo bash -lc 'export DEBIAN_FRONTEND=noninteractive; apt-get -y clean'",
	  "sudo bash -lc 'export NEEDRESTART_MODE=a; true'",
      "sudo rm -rf /var/lib/apt/lists/*",
      
      

      # 🔥 LIMPA SSH host keys (clones regeneram no 1º boot)
      "sudo rm -f /etc/ssh/ssh_host_*",

      # 🔥 LIMPA MACHINE-ID
      "sudo truncate -s 0 /etc/machine-id",
      "sudo rm -f /var/lib/dbus/machine-id",
      "sudo ln -s /etc/machine-id /var/lib/dbus/machine-id",

      # 🔥 LIMPA HISTÓRICO
      "sudo rm -f /root/.bash_history",
      "sudo rm -f /home/ubuntu/.bash_history",

      # 🔥 Reconfigura SSH (repo)
      "sudo dpkg-reconfigure openssh-server",

      # 🔥 LIMPA CLOUD-INIT COMPLETAMENTE
      "sudo cloud-init clean --logs --seed",
      "sudo rm -rf /var/lib/cloud/*",

      
      "sudo sync"
    ]
  }
}
